CREATE DATABASE IF NOT EXISTS portfolio;

USE portfolio;

CREATE TABLE IF NOT EXISTS portfolio_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  scope VARCHAR(50) NOT NULL,
  `key` VARCHAR(100) NOT NULL,
  `value` TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blog_posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(150) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL, -- for recipes, this is the intro/story before the recipe card
  category VARCHAR(100) DEFAULT 'General',
  type ENUM('article', 'recipe') NOT NULL DEFAULT 'article',
  published_at DATE NULL,
  -- Recipe-specific structured data (servings, prep/cook time, difficulty,
  -- ingredients, steps, notes, pairsWith slugs). NULL for articles. Chosen
  -- over separate ingredient/step tables since these are simple ordered
  -- lists that don't need independent querying.
  details JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio_projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  company VARCHAR(150) NOT NULL,
  company_slug VARCHAR(150) DEFAULT NULL,
  color VARCHAR(50) DEFAULT 'sky',
  tech_stack VARCHAR(255) DEFAULT NULL,
  featured TINYINT(1) DEFAULT 0,
  published TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_project_title_company (title, company_slug)
);

-- Single source of truth for work history: the homepage Experience cards, the
-- header's "Work" dropdown, and /experience/[slug] pages are all driven by
-- this table (plus its two child tables below).
CREATE TABLE IF NOT EXISTS portfolio_employers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(150) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL, -- NULL means "current / present"
  location VARCHAR(150) DEFAULT NULL,
  summary VARCHAR(500) NOT NULL, -- short blurb for the homepage preview card
  description TEXT NOT NULL,     -- longer intro shown on the employer's own page
  sort_order INT DEFAULT 0,
  color VARCHAR(20) DEFAULT NULL,           -- brand color swatch, e.g. "red"
  secondary_color VARCHAR(20) DEFAULT NULL, -- optional second swatch, e.g. "blue"
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Short bullet points shown under "What I worked on" on the employer page.
CREATE TABLE IF NOT EXISTS portfolio_employer_highlights (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employer_id INT NOT NULL,
  highlight TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  FOREIGN KEY (employer_id) REFERENCES portfolio_employers(id) ON DELETE CASCADE
);

-- Case-study cards shown under "Featured work" on the employer page.
CREATE TABLE IF NOT EXISTS portfolio_employer_case_studies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employer_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  sort_order INT DEFAULT 0,
  FOREIGN KEY (employer_id) REFERENCES portfolio_employers(id) ON DELETE CASCADE
);

-- Standalone from portfolio_employers -- a degree isn't a job, so it gets
-- its own homepage section rather than being folded into Experience.
CREATE TABLE IF NOT EXISTS portfolio_education (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(150) NOT NULL UNIQUE,
  institution VARCHAR(255) NOT NULL,
  degree VARCHAR(255) DEFAULT NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  location VARCHAR(150) DEFAULT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio_certifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(150) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  issuer VARCHAR(255) DEFAULT NULL,
  date_earned DATE NULL,
  credential_url VARCHAR(500) DEFAULT NULL,
  score VARCHAR(50) DEFAULT NULL,
  expired TINYINT(1) DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO portfolio_content (scope, `key`, `value`, sort_order) VALUES
('homepage', 'heroEyebrow', '"Family-first • software engineer • builder"', 1),
('homepage', 'heroTitle', '"I build practical internal tools that make teams faster, clearer, and more confident."', 2),
('homepage', 'heroBody', '"I’m Ryan Hurd, a software engineer focused on Retool, SQL-driven workflows, and operational tools that help people make better decisions with less friction."', 3)
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

INSERT INTO blog_posts (slug, title, excerpt, content, category, type, published_at, details) VALUES
('butter-and-cheese-pasta', 'Fettuccine with Butter and Cheese, My Way', 'A three-ingredient, cream-free pasta sauce that comes together in the time it takes the noodles to boil.', 'I''ve made this with spaghetti, fettuccine, alfredo noodles, homemade, store-bought -- honestly it doesn''t matter much, it''s all good and cheesy. It''s a fairly quick, uninvolved meal for a weeknight, and it works just as well with gluten-free pasta if that''s what you need. It''s also about as close to dairy-free as a butter-and-cheese sauce gets, since real Parmigiano-Reggiano is quite low in lactose. That said, Parmigiano-Reggiano is recommended but not required -- a good Wisconsin parmesan from your local grocery store works just fine too.

I like to top this with a blackened chicken breast (see the paired recipe), and we''ll usually round it out with store-bought garlic bread or a side of veggies depending on how we''re feeling.', 'Pasta', 'recipe', '2026-08-06', '{"servings":{"min":3,"max":4},"prepMinutes":5,"cookMinutes":20,"difficulty":"Easy","image":"/images/recipes/butter-and-cheese-pasta.svg","sourceNote":"Inspired by the classic cream-free fettuccine alfredo technique -- this is my own version, with a few tweaks (salted butter, extra cheese, and a salt garnish).","ingredients":["1 lb fettuccine (or spaghetti, or whatever noodle you have -- gluten-free works great too)","3 quarts water","1 tablespoon plus 1/2 teaspoon salt, divided","6-8 tablespoons salted butter","1 1/2 to 2 cups freshly grated Parmigiano-Reggiano (or a good Wisconsin parmesan)","Reserved starchy pasta water","A pinch of extra salt, for garnish"],"steps":["Bring the water to a boil and stir in 1 tablespoon of salt. Add the pasta and cook until al dente, stirring occasionally so it doesn''t stick.","Just before draining, scoop out about a cup of the starchy cooking water and set it aside. Drain the pasta and return it to the empty pot.","Add the butter, grated cheese, remaining 1/2 teaspoon salt, and a splash of the reserved pasta water to the pot.","Toss everything together over low heat for about a minute. It''ll look loose and watery at first -- that''s normal. Pull it off the heat, cover, and let it sit for a minute.","Uncover and toss vigorously for another 30 seconds or so, adding a little more pasta water if it needs loosening up, until the sauce turns glossy and clings to every strand.","Serve immediately in warmed bowls with a light pinch of salt on top."],"notes":["Works well with gluten-free pasta.","Nearly dairy-free, since real Parmigiano-Reggiano is quite low in lactose.","Parmigiano-Reggiano is recommended but not required -- a good Wisconsin parmesan works fine.","Great topped with blackened chicken breast, and pairs well with store-bought garlic bread or a side of veggies."],"pairsWith":["blackened-chicken-breast"]}'),
('blackened-chicken-breast', 'Blackened Chicken Breast', 'A quick, high-heat spiced chicken breast that makes a great topper for pasta, pita, or grain bowls.', 'This is my go-to protein for topping the butter and cheese pasta, stuffing into pita pockets, or piling over a grain bowl. A hot skillet and a good spice crust are really all it takes.', 'Chicken', 'recipe', '2026-08-06', '{"servings":{"min":3,"max":4},"prepMinutes":10,"cookMinutes":12,"difficulty":"Easy","image":"/images/recipes/blackened-chicken-breast.svg","sourceNote":null,"ingredients":["2 boneless, skinless chicken breasts (or 4 thin-sliced cutlets)","2 tablespoons neutral oil or melted butter","2 teaspoons smoked paprika","1 teaspoon garlic powder","1 teaspoon onion powder","1/2 teaspoon cayenne pepper (adjust to taste)","1/2 teaspoon dried thyme","1/2 teaspoon dried oregano","1 teaspoon kosher salt","1/2 teaspoon black pepper"],"steps":["Pat the chicken dry and, if the breasts are thick, slice them horizontally into thinner cutlets so they cook evenly.","Mix all the spices together in a small bowl.","Coat the chicken lightly in oil or melted butter, then press the spice mix onto both sides.","Heat a cast iron or heavy skillet over high heat until it''s very hot, almost smoking.","Lay the chicken in the skillet and cook for 3-4 minutes per side, until a dark, spiced crust forms and the internal temperature hits 165°F.","Let rest for a few minutes before slicing."],"notes":["A building-block recipe -- see the butter and cheese pasta, spinach and blue cheese quinoa bowl, and pita pockets for ways to use it."],"pairsWith":["butter-and-cheese-pasta","blackened-chicken-spinach-blue-cheese-quinoa","blackened-chicken-pita-pockets"]}'),
('blackened-chicken-spinach-blue-cheese-quinoa', 'Blackened Chicken over Spinach and Blue Cheese Quinoa', 'A from-memory re-creation of a one-off dish: creamy spinach and blue cheese over quinoa, topped with blackened chicken.', 'This was a phenomenal, mostly improvised dish that I''ll probably never recreate exactly -- but here''s my best shot at writing it down from what went into it. Lentils could stand in for the quinoa if that''s what you have on hand.', 'Chicken', 'recipe', '2026-08-06', '{"servings":{"min":2,"max":3},"prepMinutes":15,"cookMinutes":20,"difficulty":"Medium","image":"/images/recipes/blackened-chicken-spinach-blue-cheese-quinoa.svg","sourceNote":null,"ingredients":["1 jalapeno, diced","1/4 to 1/2 red onion, diced","2-3 cloves garlic, minced","1 cup frozen spinach, thawed","2-3 oz cream cheese","1-2 oz blue cheese","Cooked quinoa (lentils could work too)","Olive oil or butter","Water or chicken broth, as needed to loosen","Salt and pepper, to taste","1 batch blackened chicken breast, sliced"],"steps":["Cook the quinoa (or lentils) according to package directions and set aside as the base.","In a skillet, heat a bit of olive oil or butter and saute the jalapeno, red onion, and garlic until softened.","Stir in the thawed spinach and cook until any excess liquid evaporates.","Add the cream cheese and blue cheese, stirring until melted and combined into a creamy sauce. Thin with a splash of water or chicken broth if it''s too thick.","Season with salt and pepper to taste.","Build the bowl: quinoa on the bottom, the spinach and cheese sauce over the top, then sliced blackened chicken over that."],"notes":["A from-memory re-creation -- treat it as a starting point, not gospel.","Lentils can stand in for quinoa."],"pairsWith":["blackened-chicken-breast"]}'),
('blackened-chicken-pita-pockets', 'Blackened Chicken Pita Pockets', 'Warm pitas stuffed with blackened chicken, feta, red onion, hummus, and tzatziki.', 'Another easy way to put the blackened chicken to work -- quick to assemble and easy to customize.', 'Chicken', 'recipe', '2026-08-06', '{"servings":{"min":2,"max":4},"prepMinutes":10,"cookMinutes":0,"difficulty":"Easy","image":"/images/recipes/blackened-chicken-pita-pockets.svg","sourceNote":null,"ingredients":["Pita pockets","1 batch blackened chicken breast, sliced","Red onion, thinly sliced","Feta cheese, crumbled","Hummus","Tzatziki"],"steps":["Warm the pita pockets slightly so they''re pliable.","Spread hummus and a spoonful of tzatziki inside each pita.","Fill with sliced blackened chicken, red onion, and feta.","Fold or roll and serve."],"notes":[],"pairsWith":["blackened-chicken-breast"]}'),
('cold-smoked-cheese', 'Cold-Smoked Cheese (Brick or String)', 'Low-effort cold smoking for cheese, using nothing more than a pellet tube and a bit of patience.', 'You don''t even need a real grill for this one -- some tin foil pans, a clean brick or two, a pellet tube, heavy paper clips, and a grate work just fine, so long as things don''t get too hot. The hardest part is waiting the month it takes to mellow out in the fridge.', 'BBQ & Smoking', 'recipe', '2026-08-06', '{"servings":null,"prepMinutes":10,"cookMinutes":240,"difficulty":"Easy","image":"/images/recipes/cold-smoked-cheese.svg","sourceNote":null,"ingredients":["Brick or string cheese of your choice","Wood pellets for a pellet tube (milder woods like apple or cherry recommended)"],"steps":["Set up your smoking area so it stays cool -- this is cold smoking, not cooking, so you don''t want direct heat anywhere near the cheese. A grill works, or you can improvise with a grate set on a couple of clean bricks and some foil pans to help manage airflow.","Light your pellet tube and let it get going until it''s producing a steady stream of smoke.","Arrange the cheese on the grate, using heavy paper clips to secure string cheese pieces if needed so they don''t roll around.","Smoke for 1 to 4 hours depending on how much smoke flavor you want, keeping a close eye to make sure the cheese never starts to melt.","Let the cheese rest in the refrigerator for about a month before eating -- this gives the smoke flavor time to mellow out and distribute evenly.","Enjoy on its own, on a cheese board, or anywhere you''d use a smoked cheese."],"notes":["Be mindful of your wood choice -- stronger woods like hickory can easily overpower the cheese, so milder woods are usually a safer bet."],"pairsWith":[]}'),
('smoked-brisket', 'Smoked Brisket', 'Low and slow, fat side down, wrapped at the stall -- the full rundown for a proper smoked brisket.', 'The details matter here: a clean fat cap, a solid pellicle, and plenty of pepper for bark. Patience through the stall and a good rest at the end make all the difference. I run this on a Pit Boss CS1600, which has plenty of room -- I like tossing in two pellet tubes at once to get a little closer to a stick-burner flavor profile.', 'BBQ & Smoking', 'recipe', '2026-08-06', '{"servings":{"min":8,"max":12},"prepMinutes":30,"cookMinutes":1440,"difficulty":"Advanced","image":"/images/recipes/smoked-brisket.svg","sourceNote":null,"ingredients":["1 whole packer brisket, fat cap trimmed clean (no exposed meat/holes in the fat)","Yellow mustard, as a binder","Coarse black pepper (generous, for good bark and smoke adhesion)","Kosher salt","Any other favorite rub seasonings (garlic powder, paprika, etc.), optional","Apple cider vinegar, for spritzing (optional)","Peach butcher paper, for wrapping"],"steps":["Trim the brisket so the fat cap is smooth and solid, with no holes where the meat underneath is exposed.","Let the trimmed brisket sit uncovered in the fridge until a slightly tacky pellicle forms on the surface -- this helps the rub and smoke adhere.","Coat the brisket all over with a thin layer of mustard as a binder, then apply a generous rub of coarse pepper, salt, and any other seasonings, making sure there''s plenty of pepper for good bark and smoke adhesion.","Set up your smoker for low and slow cooking at 225-275°F and place the brisket fat side down to protect the meat from direct heat. On a smoker with the room for it (I run a Pit Boss CS1600), two pellet tubes running at once gets you closer to a stick-burner flavor -- each tube runs about 3-4 hours, so plan to swap them once or twice before the wrap.","Smoke until the brisket hits the stall, around 160°F internal temperature, spritzing occasionally with apple cider vinegar if you like. A drip pan with some ice underneath can help catch drippings and keep things moist, though it''s not required.","Wrap tightly in peach butcher paper and continue cooking until the internal temperature reaches about 200°F. Nothing special needed once it''s wrapped.","Pull the brisket and place it in a faux cambro -- a cooler lined with towels -- to rest for anywhere from 15 minutes up to a couple of hours.","Unwrap, slice against the grain, and serve. Total cook time runs roughly 24 hours depending on size -- adjust as needed to land it when you want to eat."],"notes":["Servings are approximate and depend heavily on the size of the packer brisket."],"pairsWith":["smoked-pork-shoulder"]}'),
('smoked-pork-shoulder', 'Smoked Pork Shoulder (Pulled Pork)', 'A brisket-style cook applied to pork shoulder: pellicle, mustard binder, low and slow, wrap at the stall.', 'Very similar approach to the brisket -- same Pit Boss CS1600, same dual pellet tube trick for extra smoke flavor. By the account of both an Indiana hog farmer and a Tennessee BBQ joint manager, this makes some of the best pulled pork you''ll have.', 'BBQ & Smoking', 'recipe', '2026-08-06', '{"servings":{"min":10,"max":14},"prepMinutes":20,"cookMinutes":1440,"difficulty":"Advanced","image":"/images/recipes/smoked-pork-shoulder.svg","sourceNote":"Technique passed down from an Indiana hog farmer and a Tennessee BBQ joint manager.","ingredients":["1 bone-in or boneless pork shoulder (Boston butt)","Yellow mustard, as a binder","Your favorite grilling/BBQ seasoning rub","Apple cider vinegar, for spritzing (optional)"],"steps":["Let the pork shoulder sit uncovered in the fridge until a slight pellicle forms on the surface.","Coat the shoulder in a thin layer of mustard as a binder, then apply a generous coat of your favorite grilling seasoning.","Set up your smoker at 225-275°F. Using two pellet tubes at once (I run a Pit Boss CS1600, which has the room for it) gets you closer to a stick-burner flavor profile -- each tube runs about 3-4 hours, so plan to swap them once or twice before you wrap.","Smoke until the pork hits the stall, spritzing occasionally with apple cider vinegar if you like. A drip pan with some ice underneath can help catch drippings and keep things moist, though it''s not required.","Once through the stall, wrap tightly and continue cooking -- nothing special needed once it''s wrapped.","Pull the pork once fully tender, generally in the 24-hour range total depending on size -- adjust your timeline as needed.","Rest, then shred and enjoy."],"notes":[],"pairsWith":["smoked-brisket"]}'),
('smoked-turkey', 'Smoked Turkey', 'A holiday-rotation smoked turkey, dry-brined the night before and smoked to a crisp, flavorful skin.', 'A regular on the holiday table alongside the smoked ham.', 'BBQ & Smoking', 'recipe', '2026-08-06', '{"servings":{"min":8,"max":12},"prepMinutes":30,"cookMinutes":240,"difficulty":"Medium","image":"/images/recipes/smoked-turkey.svg","sourceNote":null,"ingredients":["1 whole turkey, thawed","Butter or oil, for the skin","Salt, pepper, garlic powder, and herbs (or your favorite poultry seasoning)","Optional: onion, citrus, and herbs for the cavity"],"steps":["Dry-brine the turkey a day ahead if you can: salt it all over and let it rest uncovered in the fridge overnight to help the skin crisp and season the meat through.","Pat the turkey dry, rub the skin with butter or oil, and season generously inside and out.","Set up your smoker at 250-300°F for a good balance of smoke flavor and reasonable cook time.","Smoke until the breast hits 165°F and the thigh hits about 175°F, basting occasionally with more butter if you like a richer skin.","Let the turkey rest for 20-30 minutes before carving."],"notes":["A holiday rotation regular."],"pairsWith":["smoked-ham"]}'),
('smoked-ham', 'Smoked Ham', 'A pre-cooked spiral ham, reheated and glazed low and slow on the smoker for the holidays.', 'Another holiday rotation regular, right alongside the smoked turkey.', 'BBQ & Smoking', 'recipe', '2026-08-06', '{"servings":{"min":10,"max":16},"prepMinutes":15,"cookMinutes":150,"difficulty":"Easy","image":"/images/recipes/smoked-ham.svg","sourceNote":null,"ingredients":["1 pre-cooked spiral-cut ham","Brown sugar","Honey","A splash of apple cider vinegar or juice"],"steps":["Since a spiral ham is already fully cooked, the smoker''s job is really about reheating and adding flavor -- set up your smoker around 250°F.","Whisk together brown sugar, honey, and a splash of apple cider vinegar or juice for a simple glaze.","Smoke the ham until it reaches about 140°F internal, brushing with the glaze every 30-45 minutes so it builds up a sticky, caramelized crust.","Rest briefly, then slice along the spiral cuts and serve."],"notes":["A holiday rotation regular, alongside the smoked turkey."],"pairsWith":["smoked-turkey"]}'),
('marinated-steak', 'Marinated Steak', 'A soy-Worcestershire marinade and a ripping-hot pan or grill, cooked exactly to how rare you like it.', 'Simple, fast, and forgiving on timing -- marinate ahead, then it''s just a few minutes a side once the pan or grill is hot enough.', 'Steak', 'recipe', '2026-08-06', '{"servings":null,"prepMinutes":10,"cookMinutes":10,"difficulty":"Easy","image":"/images/recipes/marinated-steak.svg","sourceNote":null,"ingredients":["Steak(s) of your choice","Equal parts soy sauce and Worcestershire sauce (enough to submerge the steak)","A few cloves of garlic, minced or smashed","A squeeze of lemon juice (optional, helps tenderize)","Salt, to taste before cooking"],"steps":["Combine equal parts soy sauce and Worcestershire sauce in a bowl or zip-top bag, then add the garlic and a squeeze of lemon juice.","Add the steak and make sure it''s well coated. Marinate for at least an hour, though overnight in the fridge gives the best flavor.","Remove the steak from the marinade and pat it dry, then season with a touch of salt right before cooking.","Heat a skillet or grill until it''s ripping hot, around 500°F.","Cook the steak for 3-5 minutes per side depending on thickness and how done you like it -- for blue/rare, about 2.5 minutes per side is plenty.","Let the steak rest for 5-15 minutes before slicing and serving."],"notes":["Servings scale with however many steaks you''re cooking."],"pairsWith":[]}'),
('italian-beef-sandwiches', 'Italian Beef Sandwiches', 'Chicago-style thin-sliced beef, dipped in jus, topped with griddled peppers and giardiniera.', 'Inspired by classic Chicago Italian beef joints like Buona Beef. If you don''t dip it, you''re a flavorless coward.', 'Sandwiches', 'recipe', '2026-08-06', '{"servings":{"min":4,"max":6},"prepMinutes":20,"cookMinutes":180,"difficulty":"Medium","image":"/images/recipes/italian-beef-sandwiches.svg","sourceNote":"Inspired by classic Chicago Italian beef joints like Buona Beef.","ingredients":["1 beef chuck or bottom round roast","Italian beef seasoning (garlic, oregano, basil, black pepper, or a store-bought seasoning packet)","Beef broth","Italian rolls","Giardiniera","Bell peppers, sliced"],"steps":["Season the roast and slow-cook (oven, slow cooker, or braise) in beef broth with Italian seasoning until fork-tender.","Let the meat rest, then slice it as thin as you possibly can, ideally with a slicer.","Return the sliced beef to the seasoned broth (the jus) to soak up flavor and stay juicy.","Griddle the sliced bell peppers until soft and lightly charred.","Pile the beef onto an Italian roll, top with griddled peppers and giardiniera.","Dip the whole sandwich into the jus before eating -- if you''re not dipping it, you''re a flavorless coward."],"notes":["If you don''t dip it, you''re a flavorless coward."],"pairsWith":[]}'),
('honey-roasted-carrots-farro', 'Honey-Roasted Carrots with Farro', 'Simple honey-roasted carrots served over farro.', 'Props to Cindy Waddle for this one.', 'Sides', 'recipe', '2026-08-06', '{"servings":{"min":3,"max":4},"prepMinutes":10,"cookMinutes":30,"difficulty":"Easy","image":"/images/recipes/honey-roasted-carrots-farro.svg","sourceNote":"Recipe inspired by, and credit to, Cindy Waddle.","ingredients":["Carrots, peeled and cut into sticks (or left whole if small)","Honey","Olive oil","Salt and pepper","Cooked farro"],"steps":["Toss the carrots with olive oil, a drizzle of honey, salt, and pepper.","Roast in a hot oven until tender and lightly caramelized, turning once or twice.","Serve the honey-roasted carrots over a bed of cooked farro."],"notes":[],"pairsWith":[]}'),
('costco-pupusa-bowls', 'Costco Pupusa Bowls', 'Del Real Birria and Cheese Pupusas from Costco, built into a full bowl with quinoa, fire-roasted veggies, and endless toppings.', 'These make a great, easy-to-toss-together meal, and the combinations are basically endless. Get out there and try more grains -- they''re good for you and can taste phenomenal too.', 'Quick Meals', 'recipe', '2026-08-06', '{"servings":{"min":1,"max":2},"prepMinutes":15,"cookMinutes":15,"difficulty":"Easy","image":"/images/recipes/costco-pupusa-bowls.svg","sourceNote":null,"ingredients":["Del Real Birria and Cheese Pupusas (from Costco, or whatever flavor you have)","Cooked quinoa (hot or cold)","Fresh veggies: guacamole, bell peppers, lime, etc.","Tomatoes, bell peppers, and jalapenos, for fire-roasting","Optional: sour cream, cilantro, rice, or any other toppings you like"],"steps":["Cook the pupusas according to the package instructions.","To fire-roast the vegetables, place whole tomatoes, bell peppers, and jalapenos under the broiler or in a very hot oven, turning occasionally, until charred and blistered on all sides. Let cool slightly, then chop.","Build the bowl: start with a base of quinoa (hot or cold, your choice), top with the pupusas, then layer on the fire-roasted vegetables and any fresh toppings -- guacamole, lime, sour cream, cilantro, rice, whatever sounds good.","Mix and enjoy."],"notes":["A great way to work more whole grains into a meal -- they''re good for you and can taste phenomenal.","Treat this as a template, not a strict recipe -- the topping combinations are endless."],"pairsWith":["broth-cooked-quinoa"]}'),
('broth-cooked-quinoa', 'Broth-Cooked Quinoa', 'Quinoa simmered in broth instead of water -- a simple upgrade, and a good light meal when you''re feeling under the weather.', 'I used Better Than Bouillon beef broth here since it was pairing with birria- and mozzarella-flavored pupusas, but use whatever broth fits what you''re serving it with.', 'Grains', 'recipe', '2026-08-06', '{"servings":{"min":2,"max":4},"prepMinutes":5,"cookMinutes":15,"difficulty":"Easy","image":"/images/recipes/broth-cooked-quinoa.svg","sourceNote":null,"ingredients":["1 cup quinoa, rinsed","2 cups broth (Better Than Bouillon beef or chicken, or your favorite)","Salt, to taste"],"steps":["Combine the rinsed quinoa and broth in a saucepan and bring to a boil.","Reduce heat, cover, and simmer until the liquid is absorbed and the quinoa is tender, about 15 minutes.","Fluff with a fork and season with salt to taste if needed."],"notes":["Better Than Bouillon is a must in my book, but any good broth works.","Chicken broth makes this a light, easy-on-the-stomach option when you''re feeling under the weather."],"pairsWith":["costco-pupusa-bowls"]}'),
('mediterranean-grain-bowl', 'Mediterranean Grain Bowl', 'Quinoa topped with cherry tomatoes, olives, red onion, feta, cucumber, and Greek yogurt.', 'A fresh, no-cook-required bowl built around whatever grain you have on hand.', 'Grains', 'recipe', '2026-08-06', '{"servings":{"min":2,"max":3},"prepMinutes":15,"cookMinutes":0,"difficulty":"Easy","image":"/images/recipes/mediterranean-grain-bowl.svg","sourceNote":null,"ingredients":["Cooked quinoa (or similar grain)","Cherry tomatoes, halved","Kalamata or your favorite olives","Red onion, thinly sliced","Feta cheese, crumbled","Cucumber, diced","Greek yogurt"],"steps":["Start with a bed of cooked quinoa (warm or cold, whichever you prefer).","Top with cherry tomatoes, olives, red onion, feta, and cucumber.","Finish with a dollop of Greek yogurt, or stir it through as a dressing."],"notes":[],"pairsWith":[]}'),
('butter-popcorn', 'Butter Popcorn', 'Popcorn topped with clarified microwave-melted butter and popcorn salt.', 'Simple, and about as good as popcorn gets.', 'Snacks', 'recipe', '2026-08-06', '{"servings":{"min":2,"max":4},"prepMinutes":5,"cookMinutes":5,"difficulty":"Easy","image":"/images/recipes/butter-popcorn.svg","sourceNote":null,"ingredients":["1/4 to 1/2 cup popcorn kernels","1/2 to 1 stick butter","Popcorn salt"],"steps":["Pop the kernels using your preferred method (air popper, stovetop, or microwave popper).","While the popcorn pops, melt the butter in the microwave, then let it sit for a moment so the milk solids and water separate and settle to the bottom.","Carefully pour off just the clear, separated butterfat over the popcorn, leaving the milky solids behind in the container.","Toss with popcorn salt to taste."],"notes":["Separating the butterfat this way keeps the popcorn from getting soggy."],"pairsWith":[]}'),
('pineapple-upside-down-cake', 'Pineapple Upside-Down Cake with Luxardo Cherries', 'The classic caramelized pineapple cake, with Luxardo cherries standing in for the usual maraschino.', 'A classic pineapple upside-down cake, made my way with Luxardo cherries in place of maraschino -- a small swap that makes a noticeable difference.', 'Dessert', 'recipe', '2026-08-06', '{"servings":{"min":8,"max":10},"prepMinutes":20,"cookMinutes":45,"difficulty":"Medium","image":"/images/recipes/pineapple-upside-down-cake.svg","sourceNote":"A classic pineapple upside-down cake technique, made my way with Luxardo cherries in place of maraschino.","ingredients":["6 tablespoons unsalted butter (for the topping)","3/4 cup packed brown sugar","1 can (20 oz) pineapple rings, drained (juice reserved)","Luxardo cherries, drained, one for the center of each pineapple ring","1 1/2 cups all-purpose flour","1 1/2 teaspoons baking powder","1/4 teaspoon salt","1/2 cup unsalted butter, softened (for the cake)","3/4 cup granulated sugar","2 large eggs","1 teaspoon vanilla extract","1/2 cup milk (or reserved pineapple juice)"],"steps":["Preheat the oven to 350°F. Melt the 6 tablespoons of butter in a 9-inch round cake pan (or an oven-safe skillet).","Sprinkle the brown sugar evenly over the melted butter.","Arrange the pineapple rings over the brown sugar, and place a Luxardo cherry in the center of each ring.","In a bowl, whisk together the flour, baking powder, and salt.","In a separate bowl, cream the softened butter and granulated sugar together until light and fluffy. Beat in the eggs one at a time, then stir in the vanilla.","Alternate adding the dry ingredients and the milk (or pineapple juice) to the butter mixture, mixing just until combined.","Pour the batter evenly over the pineapple and cherries in the pan.","Bake for 40-45 minutes, until a toothpick inserted into the cake comes out clean.","Let the cake cool in the pan for about 10 minutes, then run a knife around the edge and invert onto a serving plate while still warm.","Serve warm or at room temperature."],"notes":["Luxardo cherries stand in for the usual maraschino cherries."],"pairsWith":[]}'),
('building-clarity-with-retool', 'Building clarity with Retool', 'A look at how thoughtful internal tooling helps teams move quickly without sacrificing reliability.', 'Retool makes it possible to build practical systems quickly, but the real value comes from pairing fast iteration with clear constraints. I''ve learned that the best tools feel invisible to the people using them while still giving leadership a strong signal about what is happening day to day.

That balance is what I aim for in most of my work: a simple interface, a reliable workflow, and enough structure to support operations without creating unnecessary friction.', 'Engineering', 'article', '2026-08-04', NULL),
('why-i-still-love-sql', 'Why I still love SQL', 'A practical reminder that clear data structures save time and reduce risk across the whole organization.', 'SQL is one of those tools that looks simple at first and becomes increasingly powerful the more you use it. It gives teams a way to ask hard questions with a small amount of syntax and a lot of clarity.

When I''m working on reporting, automation, or operational analysis, I find that the time spent shaping the data carefully almost always pays off later. It reduces handoffs, improves trust, and makes the work easier to maintain.', 'Data', 'article', '2026-08-03', NULL)
ON DUPLICATE KEY UPDATE title = VALUES(title), excerpt = VALUES(excerpt), content = VALUES(content), category = VALUES(category), type = VALUES(type), published_at = VALUES(published_at), details = VALUES(details);

INSERT INTO portfolio_projects (title, summary, image, company, company_slug, color, tech_stack, featured, published) VALUES
('Personal Portfolio', 'Built this portfolio to expand knowledge of Next.js, HeroUI, and MariaDB while showcasing professional experience.', '/images/projects/personal-portfolio.png', 'Personal Projects', 'personal-projects', 'sky', 'Next.js, HeroUI, MariaDB', 1, 1),
('Minesweeper', 'A classic Minesweeper build in Retool, exploring custom component logic and state management outside typical business apps.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Retool', 0, 1),
('Tetris', 'An in-progress Tetris build in Retool, exploring game-loop logic and state management. Still a work in progress.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Retool', 0, 1),
('Debt Calculator', 'A debt payoff planner built in Retool to compare snowball- and avalanche-style payoff ordering.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Retool', 0, 1),
('NOAA Weather Mobile App', 'A mobile weather app built in Retool against NOAA''s public weather data.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Retool', 0, 1),
('Pi-hole Network Ad Blocking', 'Set up network-wide ad blocking with Pi-hole behind Cloudflared, running on Ubuntu in VMware.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Cloudflared, VMware, Ubuntu', 0, 1),
('Synology NAS Home Server', 'Configured a Synology NAS as a home server, including MariaDB hosting, Surveillance Station and IP camera setup, port forwarding, DDNS, and Cloudflare integration.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'MariaDB, Surveillance Station, DDNS, Cloudflare, Linux', 0, 1),
('Plex Media Server', 'Built a home media server with Plex, Radarr, Sonarr, and Lidarr for media management, Discord webhooks for each *arr app, and WinNUT/BackUPS for graceful shutdown during power outages.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Plex, Radarr, Sonarr, Lidarr, WinNUT', 0, 1),
('PC Building', 'Built a PC in 2017 and have been upgrading and maintaining it ever since.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Hardware', 0, 1),
('Technology Repair', 'Repaired game consoles including PlayStation, Switch, and Xbox hardware.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Hardware repair', 0, 1),
('Household Projects', 'General contractor-style home projects: fan installation, spackling and painting, converting a bay window into a slider door, and electrical updates.', NULL, 'Personal Projects', 'personal-projects', 'sky', 'Home improvement', 0, 1),
('Yield Report', 'A reporting experience that surfaced production, material, and customer-job trends in a clearer way for operations and leadership.', '/images/projects/ppi-yield-report.svg', 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool, Excel, DL4, PKP, Access', 1, 1),
('EPA Reporting', 'A compliance-focused reporting workflow that consolidated multiple sources into a more maintainable experience.', '/images/projects/ppi-epa-reporting-screenshot.png', 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool, Excel, DL4, PKP, Access', 1, 1),
('Press WIP Optimization', 'A workflow efficiency project that reduced processing time and improved usability for day-to-day operations, improving speed by over 40%.', '/images/projects/ppi-press-wip.svg', 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool, DL4, PKP, Access', 1, 1),
('Header Module', 'A standardized header module to unify the look and navigation across locations, with email integration for ticketing and bug reports.', NULL, 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool, Email', 0, 1),
('Location Swap Application', 'Abstracted a one-off sandboxed location-switching tool into its own standalone application so other teams could benefit, and folded the same functionality into the Header Module.', NULL, 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool', 0, 1),
('Production Shift Report Module', 'An in-progress Retool tool letting shift leads log scrap and production statistics digitally instead of on paper, eventually pulling data directly from machines. Still a work in progress.', NULL, 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool', 0, 1),
('Slitter WIP Optimization', 'Advised on load-speed optimizations for the Slitter WIP process, helping cut load speed by 30-40%.', NULL, 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Process optimization', 0, 1),
('Timeclock Workflow Optimization', 'Optimized the PunchAndReset, Punching, and BadgeAndPin timeclock workflows, letting employees punch in/out and manage PINs by badge or PIN entry.', NULL, 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool Workflows', 0, 1),
('AI-Assisted Development Practices', 'Explored practical ways to work effectively with AI tools for planning, implementation, and verification.', NULL, 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'Retool AI, ChatGPT', 0, 1),
('Data Governance & Housekeeping', 'General housekeeping, data governance, database normalization, and resource management work across Retool applications.', NULL, 'Packaging Personified, Inc.', 'packaging-personified', 'sky', 'PostgreSQL, SQL', 0, 1),
('Contacts Database', 'Built and maintained a centralized contacts database.', NULL, 'Sweetwater Sound', 'sweetwater-sound', 'sky', '4D', 0, 1),
('4D SQL Engine Restrictions', 'Restricted non-senior engineers from running expensive SQL keywords like HAVING and WITH that were taxing the system.', NULL, 'Sweetwater Sound', 'sweetwater-sound', 'sky', '4D', 0, 1),
('Press Release Management', 'Let staff post and maintain press releases, including images, directly to the Sweetwater website.', NULL, 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Web Text Editor', 'Attempted a WYSIWYG-style editor for the web team to update product text and images directly. Record-locking limitations in Retool, and the lack of true drag-and-drop, ultimately kept it from shipping even after getting close.', NULL, 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Beverage Kiosks', 'Rewrote the shared beverage kiosk application to improve consistency and maintainability across multiple kiosk locations.', '/images/projects/beverage-kiosks.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Crescendo Cafe Kiosk', 'Rebuilt the cafe management system with Retool to improve usability, performance, and long-term maintainability.', '/images/projects/crescendo-cafe-kiosk.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Consumer Audio', 'Reworked the round-robin assignment flow for less specialized audio equipment sales to reduce sales engineer workload and increase throughput.', '/images/projects/consumer-audio.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', '4D', 0, 1),
('Distribution Center Cookout Giveaway', 'Built a badge-based raffle application for the Sweetwater Distribution Center to manage employee prizes and winners at a cookout event.', '/images/projects/dc-cookout-giveaway.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('End of Day Notes', 'Created a shared handoff application for the Guitar Gallery to centralize daily notes and improve shift transitions.', '/images/projects/end-of-day-notes.png', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Gear Exchange - Braintree Implementation', 'Integrated PayPal''s Braintree payment processing into Gear Exchange, enabling secure transactions and helping bring the platform to life. Gear Exchange saw over $1M in sales within its first few months.', '/images/projects/gear-exchange.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', '4D, PayPal Braintree GraphQL API', 1, 1),
('Gitlab Permissions Lookup', 'Created a tool that uses the GitLab REST API to surface repository ownership and maintainers for support teams.', '/images/projects/gitlab-permissions-lookup.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool, GitLab API', 0, 1),
('In-House Credit Freezing/Thawing', 'Modified the logic related to freezing and thawing credits to comply with Indiana state law and improve financial accuracy.', '/images/projects/credit-freezing-thawing.png', 'Sweetwater Sound', 'sweetwater-sound', 'sky', '4D', 0, 1),
('Inventory Variances', 'Built an app to help the Music Store track inventory variances and maintain stock more effectively.', '/images/projects/inventory-variances.png', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Mentor Management Application', 'Built with the Orbital class team, this app helped mentees select mentors over a set period to support learning and skill-building.', '/images/projects/mentor-management.png', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'C#/.NET, Go/GCP', 0, 1),
('Personalized Tile Promotions', 'Rewrote the Personalized Tile Promotions application to show targeted promotions based on browsing history.', '/images/projects/personalized-tile-promotions.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Price Management Platform', 'Built a pricing-tracking tool for the merchandising team that helped sharpen competitor pricing insight, driving $4M in increased revenue in under a month.', '/images/projects/price-management-platform.png', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 1, 1),
('Search Miner', 'Developed a tool to help the SEO engineer analyze Sweetwater.com search results and improve website health and performance.', '/images/projects/search-miner.png', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Tax Exemption Certification Management System (ECMS)', 'Sole developer on implementing Avalara''s Exemption Certificate Management System, saving the tax team the equivalent of 160+ hours of validating certificates per month.', '/images/projects/ecms.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', '4D, ECM/ECMS API', 1, 1),
('Turkey Handout Application', 'Delivered a Thanksgiving turkey/gift card handout tool within 72 hours, letting the campus events team serve 2,500 employees.', '/images/projects/turkey-handout.png', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 1, 1),
('Wavelengths Salon & Spa Kiosk', 'Provided support and maintenance for the Wavelengths Salon and Spa internal platform with a focus on usability and bug fixes.', '/images/projects/wavelengths-salon-spa-kiosk.jpg', 'Sweetwater Sound', 'sweetwater-sound', 'sky', 'Retool', 0, 1),
('Mentoring and Training', 'Trained engineers new to 4D, including an electrical engineer without a CS background and a senior engineer transitioning from another team, plus ongoing mentoring in code reviews and meetings.', NULL, 'Sweetwater Sound', 'sweetwater-sound', 'sky', '4D', 0, 1),
('Device Tracking Spreadsheet', 'Built an Excel tracking sheet for assigned devices to reduce hand-off errors from manual tracking.', NULL, 'Zimmer Biomet', 'zimmer-biomet', 'sky', 'Excel', 0, 1),
('Accessibility Website', 'Built a website teaching accessibility concepts using Agile methodologies as part of a project management course.', '/images/projects/accessibility-website.jpg', 'Purdue University', 'purdue-university', 'sky', 'React', 0, 1),
('DementiaTrack', 'A senior capstone project that analyzed patient sensor data to explore sensor-based health monitoring and machine learning insights.', '/images/projects/dementiatrack.jpg', 'Purdue University', 'purdue-university', 'sky', 'Python, React', 0, 1),
('Flashcards Android Application', 'Built a Flashcards app as part of a software engineering course.', '/images/projects/flashcards-android.jpg', 'Purdue University', 'purdue-university', 'sky', 'Kotlin, Android Studio', 0, 1),
('Website Development - Final Project', 'Built a website for Black''s Concrete Construction as a functional final project for coursework.', '/images/projects/website-development-final-project.png', 'Ivy Tech', 'ivy-tech', 'sky', 'HTML5, CSS3', 0, 1),
('Phase 10 Dice', 'Developed the Phase 10 Dice game as the final project for an introductory programming course.', '/images/projects/phase-10-dice.jpg', 'Ivy Tech', 'ivy-tech', 'sky', 'C++', 0, 1),
('Banking Application', 'Built a banking application as a course project.', NULL, 'Ivy Tech', 'ivy-tech', 'sky', 'C++', 0, 1)
ON DUPLICATE KEY UPDATE summary = VALUES(summary), image = VALUES(image), company = VALUES(company), color = VALUES(color), tech_stack = VALUES(tech_stack), featured = VALUES(featured), published = VALUES(published);

-- Employers: single source of truth for homepage Experience cards, the
-- header's Work dropdown, and /experience/[slug] pages.
INSERT INTO portfolio_employers (slug, name, title, start_date, end_date, location, summary, description, sort_order, color, secondary_color) VALUES
('packaging-personified', 'Packaging Personified, Inc.', 'Software Engineer', '2025-10-01', NULL, 'Warsaw, IN', 'Building internal Retool applications for production, compliance, accounting, and operations teams.', 'Building internal Retool applications for production, compliance, accounting, and operations teams, including a Yield Report tool for tracking job performance and material usage, and consolidated EPA reporting for Illinois and Michigan compliance. Created reusable shared modules and delivered a 40%+ performance improvement to the Press WIP application while training managers and end users on Retool best practices.', 1, 'emerald', NULL),
('sweetwater-sound', 'Sweetwater Sound', 'Software Engineer', '2021-05-01', '2025-08-01', 'Fort Wayne, IN', 'Delivered internal tools, workflow automations, and revenue-driving platforms across accounting, commerce, and merchandising.', 'Sole developer of Avalara''s Exemption Certificate Management System, saving the tax team 160+ hours of manual validation per month, and integrated PayPal''s Braintree system into the CRM to help launch Gear Exchange, which generated over $1M in sales within months. Also built a dynamic Price Management Platform that drove $4M in revenue in under a month, alongside daily-use internal tools across departments.', 2, 'red', NULL),
('zimmer-biomet', 'Zimmer Biomet', 'Information Technology Intern', '2020-10-01', '2021-05-01', 'Warsaw, IN', 'Supported device deployment and IT operations across campuses in the Warsaw area.', 'Imaged and deployed company devices, issued laptops and accessories, and performed hardware upgrades for onboarding and refresh cycles. Delivered devices to campuses across the Warsaw area as part of IT operations support.', 3, 'blue', NULL),
('census-bureau', 'United States Census Bureau', 'Post-Enumeration Surveyor', '2020-01-01', '2020-10-01', 'Warsaw, IN', 'Collected population data door-to-door for the U.S. Census Bureau''s Post-Enumeration Survey.', 'Conducted in-person interviews to collect population data for the Post-Enumeration Survey, ensuring census accuracy while complying with strict federal confidentiality guidelines. Maintained detailed activity logs and navigated difficult resident interactions with calm, professional de-escalation.', 4, 'red', 'blue'),
('staples', 'Staples', 'Technology Sales Associate', '2018-06-01', '2019-05-01', 'Warsaw, IN', 'Helped customers find the right technology products as a top-performing sales associate.', 'Assessed customer needs and guided them to the right technology products, consistently ranking as the top store in Northern Indiana for several consecutive weeks. Stayed current on promotions and product launches to support sales goals.', 5, 'amber', NULL),
('blacks-concrete-construction', 'Black''s Concrete Construction', 'Concrete Laborer', '2016-06-01', '2017-03-01', 'Warsaw, IN', 'Handled nearly every phase of residential concrete work on a small, hands-on crew.', 'Worked as part of a small 2-3 person crew handling nearly every phase of residential concrete work, including driving the company truck, forming, pouring, finishing, cutting, cleaning, sealing, and stamping. Gained hands-on versatility and a strong work ethic from taking on broad responsibility within a lean, close-knit team.', 6, 'black', 'white')
ON DUPLICATE KEY UPDATE name = VALUES(name), title = VALUES(title), start_date = VALUES(start_date), end_date = VALUES(end_date), location = VALUES(location), summary = VALUES(summary), description = VALUES(description), sort_order = VALUES(sort_order), color = VALUES(color), secondary_color = VALUES(secondary_color);

-- Highlights and case studies are seed-only (no natural unique key), so clear
-- any existing rows for these employers before re-inserting on a fresh run.
DELETE h FROM portfolio_employer_highlights h JOIN portfolio_employers e ON e.id = h.employer_id
  WHERE e.slug IN ('packaging-personified', 'sweetwater-sound', 'zimmer-biomet', 'census-bureau', 'staples', 'blacks-concrete-construction');
DELETE c FROM portfolio_employer_case_studies c JOIN portfolio_employers e ON e.id = c.employer_id
  WHERE e.slug IN ('packaging-personified', 'sweetwater-sound', 'zimmer-biomet');

INSERT INTO portfolio_employer_highlights (employer_id, highlight, sort_order)
SELECT e.id, h.highlight, h.sort_order FROM portfolio_employers e
JOIN (
  SELECT 'packaging-personified' AS slug, 1 AS sort_order, 'Developed and maintained internal applications using Retool, PostgreSQL, SQL, and JavaScript for production, compliance, accounting, and operations teams.' AS highlight
  UNION ALL SELECT 'packaging-personified', 2, 'Built the Yield Report application to track company and customer job performance, material usage, production efficiency, and operational trends.'
  UNION ALL SELECT 'packaging-personified', 3, 'Consolidated spreadsheets and multiple data sources into EPA reporting tools supporting environmental compliance workflows for Illinois and Michigan facilities.'
  UNION ALL SELECT 'packaging-personified', 4, 'Created reusable tools, including a standardized Header Module and scalable Location Swap application, to improve consistency across Retool applications.'
  UNION ALL SELECT 'packaging-personified', 5, 'Optimized applications and automated workflows for performance, reliability, and usability, including improving Press WIP processing speed by more than 40%.'
  UNION ALL SELECT 'packaging-personified', 6, 'Trained managers, developers, company owners, and end users on Retool functionality, application workflows, and development best practices.'
  UNION ALL SELECT 'sweetwater-sound', 1, 'Sole developer on the implementation of Avalara''s Exemption Certificate Management System (ECMS), saving the tax team the equivalent of 160+ hours of validating exemption certificates per month.'
  UNION ALL SELECT 'sweetwater-sound', 2, 'Integrated PayPal''s GraphQL-based Braintree system into the CRM to help launch Gear Exchange, which saw over $1M in sales between users within its first few months.'
  UNION ALL SELECT 'sweetwater-sound', 3, 'Built and deployed a Price Management Platform used by merchandising to adjust pricing dynamically, resulting in $4M in increased revenue in under a month.'
  UNION ALL SELECT 'sweetwater-sound', 4, 'Provided a Turkey Handout application for Sweetwater''s Thanksgiving giveaway within 72 hours, allowing the campus events team to hand out turkeys and gift cards to 2,500 employees.'
  UNION ALL SELECT 'sweetwater-sound', 5, 'Contributed to internal software development by designing scalable features, debugging production issues, and delivering tools used daily across multiple departments.'
  UNION ALL SELECT 'zimmer-biomet', 1, 'Imaged and prepared company devices with software for deployment.'
  UNION ALL SELECT 'zimmer-biomet', 2, 'Issued laptops, accessories, and performed hardware upgrades for onboarding and refreshing hardware.'
  UNION ALL SELECT 'zimmer-biomet', 3, 'Used a company vehicle to deliver devices to various campuses in the Warsaw area.'
  UNION ALL SELECT 'census-bureau', 1, 'Performed interviews at addresses within assigned blocks to collect population data as part of the Post-Enumeration Survey, ensuring census accuracy.'
  UNION ALL SELECT 'census-bureau', 2, 'Complied with strict federal guidelines and confidentiality rules for gathering demographic and housing information.'
  UNION ALL SELECT 'census-bureau', 3, 'Recorded information using a government-issued laptop, maintaining hour logs, mileage, and case activity.'
  UNION ALL SELECT 'census-bureau', 4, 'Navigated difficult or uncooperative situations by calmly diffusing tensions with hesitant or hostile residents.'
  UNION ALL SELECT 'staples', 1, 'Asked customers pertinent questions to assess and determine their needs, guiding them to the correct product.'
  UNION ALL SELECT 'staples', 2, 'Answered questions, explained product features, and gave honest input based on customer needs.'
  UNION ALL SELECT 'staples', 3, 'Used Staples sales strategies to become the number one store in Northern Indiana for several weeks straight.'
  UNION ALL SELECT 'staples', 4, 'Stayed up to date on weekly promotions and product launches to best support customers and hit sales goals.'
  UNION ALL SELECT 'blacks-concrete-construction', 1, 'Drove the company truck and handled nearly every phase of residential concrete work on a lean 2-3 person crew.'
  UNION ALL SELECT 'blacks-concrete-construction', 2, 'Performed forming, pouring, finishing, cutting, cleaning, sealing, and stamping across a wide range of jobs.'
  UNION ALL SELECT 'blacks-concrete-construction', 3, 'Gained hands-on versatility and a strong work ethic from taking on broad responsibility within a small, close-knit team.'
) h ON h.slug = e.slug;

INSERT INTO portfolio_employer_case_studies (employer_id, title, summary, image, sort_order)
SELECT e.id, c.title, c.summary, c.image, c.sort_order FROM portfolio_employers e
JOIN (
  SELECT 'packaging-personified' AS slug, 'Yield Report' AS title, 'A reporting tool for tracking production and customer performance trends using operational data from multiple sources.' AS summary, '/images/projects/ppi-yield-report.svg' AS image, 1 AS sort_order
  UNION ALL SELECT 'packaging-personified', 'EPA Reporting', 'A compliance-oriented reporting workflow that combines spreadsheets and source data into a more maintainable reporting experience.', '/images/projects/ppi-epa-reporting-screenshot.png', 2
  UNION ALL SELECT 'packaging-personified', 'Press WIP Optimization', 'A performance-focused workflow improvement project that reduced processing time and simplified day-to-day operations.', '/images/projects/ppi-press-wip.svg', 3
  UNION ALL SELECT 'sweetwater-sound', 'Turkey Handout App', 'A fast-turnaround internal tool that made holiday employee gifting easier and more organized.', '/images/projects/turkey-handout.png', 1
  UNION ALL SELECT 'sweetwater-sound', 'Gear Exchange', 'Helped support commerce workflows and secure payment integration for a rapidly growing platform.', '/images/projects/gear-exchange.jpg', 2
  UNION ALL SELECT 'sweetwater-sound', 'DementiaTrack', 'A capstone project that combined thoughtful software design with practical analytics.', '/images/projects/dementiatrack.jpg', 3
  UNION ALL SELECT 'zimmer-biomet', 'Device Deployment Support', 'Helped prepare and configure systems for company use in a structured, detail-focused workflow.', NULL, 1
) c ON c.slug = e.slug;
INSERT INTO portfolio_education (slug, institution, degree, start_date, end_date, location, sort_order) VALUES
('whitko', 'Whitko Community High School', 'Core 40 – Academic Honors Diploma', '2011-08-01', '2016-05-01', 'South Whitley, IN', 1),
('ivy-tech', 'Ivy Tech Community College', 'Associate of Science, Computer Science', '2017-01-01', '2019-05-01', 'Warsaw/Fort Wayne, IN', 2),
('purdue-fort-wayne', 'Purdue University Fort Wayne', 'Bachelor of Science, Computer Science', '2019-08-01', '2021-05-01', 'Fort Wayne, IN', 3)
ON DUPLICATE KEY UPDATE institution = VALUES(institution), degree = VALUES(degree), start_date = VALUES(start_date), end_date = VALUES(end_date), location = VALUES(location), sort_order = VALUES(sort_order);

INSERT INTO portfolio_certifications (slug, name, issuer, date_earned, credential_url, score, expired, sort_order) VALUES
('python-pcep', 'Python PCEP Certification', 'Python Institute', '2021-09-01', NULL, NULL, 0, 1),
('comptia-a-plus', 'CompTIA A+', 'CompTIA', '2017-12-01', NULL, '1880', 1, 2),
('retool-platform-admin', 'Retool Platform Admin', 'Retool', '2025-03-01', NULL, NULL, 0, 3),
('retool-platform-developer', 'Retool Platform Developer', 'Retool', '2025-03-01', NULL, NULL, 0, 4)
ON DUPLICATE KEY UPDATE name = VALUES(name), issuer = VALUES(issuer), date_earned = VALUES(date_earned), credential_url = VALUES(credential_url), score = VALUES(score), expired = VALUES(expired), sort_order = VALUES(sort_order);
